name: Markdownlint

on:
  pull_request:
    paths:
    - ".github/workflows/markdownlint-problem-matcher.json"
    - ".github/workflows/markdownlint.yml"
    - ".markdownlint.json"
    - "package*.json"
    - "**/*.md"

  push:
    branches-ignore:
    - "dependabot/**"
    paths:
    - ".github/workflows/markdownlint-problem-matcher.json"
    - ".github/workflows/markdownlint.yml"
    - ".markdownlint.json"
    - "package*.json"
    - "**/*.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Markdownlint
        run: |
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          npm run lint
